version = 1

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "dependency"
enabled = true

[python]
python_version = ["3.9"]

[python.test_patterns]
  - "tests/**/*.py"
  - "test_*.py"
  - "*_test.py"

[python.coverage]
  - "simulation/**/*.py"
  - "config/**/*.py"
  - "utils/**/*.py"
  - "app.py"
  - "dash_app.py"
  - "main.py"

[python.ignore_patterns]
  - "tests/**/*"
  - "validation/**/*"
  - "archive/**/*"
  - "backup/**/*"
  - "docs/**/*"
  - "browser_logs/**/*"
  - "logs/**/*"
  - "assets/**/*"
  - "static/**/*"
  - "templates/**/*"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/*.pyo"
